"""tenant leases and used risk tokens

Revision ID: 419721c785b4
Revises: e8ef2a671061
Create Date: 2026-09-10 18:08:52.735934

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '419721c785b4'
down_revision: str | None = 'e8ef2a671061'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_leases',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('fencing_token', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('used_risk_tokens',
    sa.Column('token_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('used_risk_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_used_risk_tokens_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_risk_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_used_risk_tokens_tenant_id'))

    op.drop_table('used_risk_tokens')
    op.drop_table('tenant_leases')
    # ### end Alembic commands ###
