"""add signal reference_price

Revision ID: 4d3a2730fb9a
Revises: d0d00ec22139
Create Date: 2026-09-10 02:54:21.478972

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d3a2730fb9a'
down_revision: str | None = 'd0d00ec22139'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('reference_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'reference_price')
    # ### end Alembic commands ###
