"""multi-tenant data model

Revision ID: 6b74cc33b5df
Revises: fd58ea0e93ca
Create Date: 2026-09-10 17:48:42.000106

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6b74cc33b5df'
down_revision: str | None = 'fd58ea0e93ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_agent_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_agent_runs_tenant_stock', ['tenant_id', 'stock_symbol'], unique=False)
        batch_op.create_foreign_key('fk_agent_runs_tenant_id_users', 'users', ['tenant_id'], ['id'])

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        # PK becomes composite (tenant_id, key) -- one row per tenant per
        # setting key, not one global row per key. Autogenerate doesn't
        # detect primary-key changes, so this is added by hand.
        batch_op.create_primary_key('pk_app_settings', ['tenant_id', 'key'])
        batch_op.create_foreign_key('fk_app_settings_tenant_id_users', 'users', ['tenant_id'], ['id'])

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_audit_log_tenant_id_users', 'users', ['tenant_id'], ['id'])

    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_backtest_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_backtest_runs_tenant_id_users', 'users', ['tenant_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_orders_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_orders_tenant_id_users', 'users', ['tenant_id'], ['id'])

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_positions_stock_symbol'))
        batch_op.create_index(batch_op.f('ix_positions_stock_symbol'), ['stock_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_positions_tenant_symbol', ['tenant_id', 'stock_symbol'])
        batch_op.create_foreign_key('fk_positions_tenant_id_users', 'users', ['tenant_id'], ['id'])

    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_risk_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_risk_events_tenant_id_users', 'users', ['tenant_id'], ['id'])

    with op.batch_alter_table('risk_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')
        # tenant_id IS the primary key now -- one risk-state row per tenant,
        # replacing the old id=1 singleton. Autogenerate doesn't detect
        # primary-key changes, so this is added by hand.
        batch_op.create_primary_key('pk_risk_state', ['tenant_id'])
        batch_op.create_foreign_key('fk_risk_state_tenant_id_users', 'users', ['tenant_id'], ['id'])

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_signals_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_signals_tenant_stock', ['tenant_id', 'stock_symbol'], unique=False)
        batch_op.create_foreign_key('fk_signals_tenant_id_users', 'users', ['tenant_id'], ['id'])

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_stocks_symbol'))
        batch_op.create_index(batch_op.f('ix_stocks_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_stocks_tenant_symbol', ['tenant_id', 'symbol'])
        batch_op.create_foreign_key('fk_stocks_tenant_id_users', 'users', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stocks_tenant_id_users', type_='foreignkey')
        batch_op.drop_constraint('uq_stocks_tenant_symbol', type_='unique')
        batch_op.drop_index(batch_op.f('ix_stocks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_stocks_symbol'))
        batch_op.create_index(batch_op.f('ix_stocks_symbol'), ['symbol'], unique=1)
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_signals_tenant_id_users', type_='foreignkey')
        batch_op.drop_index('ix_signals_tenant_stock')
        batch_op.drop_index(batch_op.f('ix_signals_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('risk_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_risk_state_tenant_id_users', type_='foreignkey')
        batch_op.drop_constraint('pk_risk_state', type_='primary')
        batch_op.create_primary_key('pk_risk_state', ['id'])
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_risk_events_tenant_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_risk_events_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_positions_tenant_id_users', type_='foreignkey')
        batch_op.drop_constraint('uq_positions_tenant_symbol', type_='unique')
        batch_op.drop_index(batch_op.f('ix_positions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_positions_stock_symbol'))
        batch_op.create_index(batch_op.f('ix_positions_stock_symbol'), ['stock_symbol'], unique=1)
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_tenant_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_backtest_runs_tenant_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_backtest_runs_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_log_tenant_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_app_settings_tenant_id_users', type_='foreignkey')
        batch_op.drop_constraint('pk_app_settings', type_='primary')
        batch_op.create_primary_key('pk_app_settings', ['key'])
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_runs_tenant_id_users', type_='foreignkey')
        batch_op.drop_index('ix_agent_runs_tenant_stock')
        batch_op.drop_index(batch_op.f('ix_agent_runs_tenant_id'))
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
