"""risk state table

Revision ID: bf0310504d98
Revises: 4d3a2730fb9a
Create Date: 2026-09-10 03:02:23.882007

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf0310504d98'
down_revision: str | None = '4d3a2730fb9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_mode', sa.String(length=32), nullable=False),
    sa.Column('daily_realized_pnl', sa.Float(), nullable=False),
    sa.Column('daily_pnl_date', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('kill_switch_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switch_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('risk_state')
    # ### end Alembic commands ###
